### PR TITLE
Update Polymer URLs for Bundle

### PR DESCRIPTION
**Pull request by MrSerth**
This PR mainly includes some changes to be conform with official Polymer recommendations. As we use several Polymer elements in Xikolo, it is advantageous to stick to some guidelines to prevent loading the same code multiple times in a browser. Unfortunately, Polymer does not include sufficient mechanisms to detect duplicate code (such as the Polymer element itself or other externally provided custom elements, such as `custom-style`). It only relies on de-duplication through the browser if multiple elements refer to the same html import. If, for example, the video-player and the [mammooc-rating-widget](https://github.com/mammooc/mammooc-rating-widget) should be used on the same page, we are required to ensure that no dependency is loaded twice in the browser. Therefore, the URLs are required to point to the same resources. Until now, the video-player and the mammooc-rating-widget differed in the URLs used, so that one of them needs to be updated. After looking in the Polymer documentation and example code on GitHub, I decided to create this PR. Following the example from the [Polymer beginners guide](https://www.polymer-project.org/2.0/start/first-element/step-2) and in advance of the approaching Polymer 3 update, I dropped the reference for the `bower_components` folder in the URL. The URL pattern used in the video-player so far was somehow supported by the web server `polymer serve`, but as far as I know, it is not the best way. 

The two screenshots attached show a difference in the handling of the files by `polymer serve`. In the first example, the desired URL is used and the served page directly starts with a `dom-module`. The second image shows the supported but error-prone way, which also includes the usually required html tags. As this file is only used as an import, these default html tags are not required. I adopted the URLs for both, the `bower_components` and the `node_modules` to match Polymer guidelines. 

This change makes the import relationship between the files also independent from the server, which further allows us to publish it with a static web server, such as GitHub pages. The only requirement for an automated deployment process is that the name of this repository matches the element name (see issue #38). I included a slightly adopted deploy script for GitHub pages to deal with the npm dependencies as well and prepared a possible name of this repo.

Please visit the GitHub pages demo of my fork for a working demo of the proposed changes: https://mrserth.github.io/video-player/

If this PR is merged, I would require a formal release of the video-player to continue bundling the video-player with the mammooc-rating-widget. This work will result in one html import file called [polymer-xikolo](https://github.com/openHPI/polymer-xikolo/) to prevent any conflicts with multiple Polymer elements on one page.

Serving the unmodified file via `polymer serve`:
direct

Slightly modified file served from a virtual location via `polymer serve`:
component

### CODE REVIEW

**Comment by franzliedke** [comment]
I am not sure we want to host polymer-xikolo on GitHub, but other than that, this looks like a great improvement. Well done. :+1:

**Comment by jprberlin** [comment]
I am fine with hosting this on github as it’s bundling only openSource components.

**Comment by jprberlin** [comment]
@sebastiankliem Can you trigger a release?

**Comment by franzliedke** [comment]
@jprberlin The problem is hosting it here, managing access here and on private GitLab. IMO it belongs into xikolo-web.

**Comment by jprberlin** [comment]
Not if on the long term you would like to see Xikolo open sourced :)

**Comment by franzliedke** [comment]
But then move all of it there. I have no interest in managing our asset pipeline in two different places, it's already complicated enough.

**Comment by jprberlin** [comment]
Ok, feel free to move it to GitLab. We could also dicuss make it public there.

**Comment by tobiasrohloff** [comment]
@MrSerth unfortunately you worked directly on the master branch and missed some commits from [dev](https://github.com/openHPI/video-player/tree/dev). They have conflicts now. Could you please take care of them, since you know best how to deal with the dependency changes? I wanna merge three branches based on dev and release them, which is not possible at the moment for me:

- #31 / [#31_screen_orientation](https://github.com/openHPI/videoplayer/tree/%2331_screen_orientation)
- #33 / [#33_volume_change](https://github.com/openHPI/videoplayer/tree/%2333_volume_change)
- #35 / [#35_expose_slide_number](https://github.com/openHPI/videoplayer/tree/%2335_expose_slide_number)

Did you tested the video player after your changes? Did anything changed about the release process as described in the readme?

/cc @franzliedke @jprberlin

**Comment by tobiasrohloff** [comment]
@MrSerth I've merged the three branches into dev and opened a PR for you that now includes all changes that needs to merged into master: https://github.com/openHPI/video-player/pull/43

**Comment by MrSerth** [comment]
@franzliedke Regarding `polymer-xikolo`: As @jprberlin already mentioned, the repository is not going to contain anything that is not available in either this repository or the mammooc-rating-widget. If we move it, it cannot be accessed through a public repository, such as bower (which currently is still the preferred way for Polymer elements). I don't have any experience on how to deal with private elements for the build process and cannot estimate the required affords.

**Comment by MrSerth** [comment]
@tobiasrohloff I am sorry for any inconvenience caused. I feel, you are very frustrated with my work, which is the last thing I intended. I do welcome feedback and I am sure, we can clarify some of our mutual misunderstandings together. Besides my comments below, I am open-minded to a person-to-person dialog within the next few days at HPI.

As you mentioned, yes, I worked directly on the master branch. Nevertheless, I checked the code for any hints on contribution guidelines, which I was unable to find. Therefore, I stuck to the development process I know from the main Xikolo development, where this approach is well-established. Except that, I am new to this code base here and did not take a look into all 27 branches. 

I can also have a look at your new PR and resolve as many merge conflicts as possible, even though I do not know exactly why the 3rd-imports are used in the way the dev uses them. The one thing I can do (which is the same as I did here) is to ensure that no of the URLs is absolute and that no URL include `bower_components` (which should not be included for various ways as recommended by the Polymer project authors). 

In general, I always test my changes prior to pushing and especially prior to a PR for a master branch in another repository. In this case, I extended my tests and used various ways to find mistakes. To be precisely, I tested it locally (using `polymer serve`) with macOS Sierra 10.12.6 using Safari 11, Chrome 61 and Firefox 55. In addition, I accessed the published version (on my GitHub pages branch) and executed the same tests using the same three browsers on my Mac and in addition used the mobile Safari (iOS 11). In my tests, I checked the visuals, started the video playback, changed the playback speed and quality, enabled the captions and transcript in different languages and checked for the table of content. If I was not sure about some behavior (such as the "full screen" mode on iOS, which does not hide the top UI in Safari with the URL), I compared my working version with the live version on open.hpi.de (where in this case the same behavior occurs). Especially because of my work on the URLs, I also used a network inspector to find erroneous HTTP response codes, which I resolved if found. Besides my manual tests, I used the test suite to run the automated tests on my machine and on travis. In both cases, I did not find any further error. Nevertheless, let me add a side note to my demo on GitHub pages: The configuration tries to access the slide thumbnails on testing.openhpi.de which is password protected. In my tests, I noticed that some browers display a prompt to enter credentials, where others don't. This might result in empty slide thumbnails, if the browser could not authenticate. 
Did you found any bugs introduced with my changes? Please feel free to describe them in a specific way, so that I can try to reproduce them. Regarding your question, yes, I did test the video-player after I applied my changes.

Regarding the release process: I did include two more steps for the release process to automatically publish a working demo to a GitHub pages branch. The script included is provided by the Polymer project and has been adopted by my to work with the npm dependencies (e.g. font-awesome). These steps are fully integrated into the npm deploy script and do not require any manual action. Therefore, the release process has not been changed for a developer, and (as written in the readme), only `npm run deploy [major|minor|patch]` has to be executed.

I hope, that my text helps to clarify and to relax the situation. Please keep in mind, that I only started to work on this project to enable the video-player and the mammooc-rating-widget on the same page to revert the web MR 688 (in Gitlab). 

I would like to excuse my shortcomings you noticed regarding this PR. Let's work together to solve the current problems.

/cc @franzliedke @jprberlin

**Comment by tobiasrohloff** [comment]
@MrSerth don't worry, I'm not frustrated with your work at all. I'm very happy about your support and really appreciate that. Thank you again for solving the conflicts from dev. Your right, there are no dev guidelines at all.

We have to improve the process for the development and release of the video-player. This is what frustrates me at the moment. Excuse me, if I blamed you a bit for that, it is not your project and not your fault at all.

**Comment by franzliedke** [comment]
@MrSerth As far as I understand, the purpose of [polymer-xikolo](https://github.com/openHPI/polymer-xikolo/) is to generate one large HTML import that includes both `mammooc-rating-widget` and `video-player`.

This is totally Xikolo-specific and probably not useful for anyone else, which is why I suggested to move it to Xikolo's asset pipeline. We won't need this combined HTML import to be available through Bower, we just need to dump it on our servers. :wink:

**Comment by MrSerth** [comment]
@franzliedke Okay, if we do not require it there, I am fine with hosting it on GitLab. Could you please create an empty repository for me? Thanks!

**Comment by franzliedke** [comment]
Why can't we do it in xikolo-web? All other parts of the asset build pipeline are there.

**Comment by MrSerth** [comment]
The structure of the project will be similar to the one of the `video-player` / `mammooc-rating-widget` except that the `src` folder will only contain one file with other imports. I'll finish my work on combining that and will step by soon.

**Comment by tobiasrohloff** [comment]
Just a side note: We have do to the same for https://github.com/openHPI/m.e.i.n.e.l

**Comment by MrSerth** [comment]
Yes, on the long, you're right. Nevertheless, this element is still Polymer 1.0 and might need to be updated prior to bundling it. For now, it's hard enough to find a proper way for the class-based Polymer 2.0 elements only.

**Pull request merged**
